/* DO NOT EDIT THIS FILE - it is machine generated */

#include "../../../../../../../../AndroidSdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_example_emmc_NDKTest */

#ifndef _Included_com_example_emmc_NDKTest
#define _Included_com_example_emmc_NDKTest
#ifdef __cplusplus

extern "C"{
#endif

    JNIEXPORT jstring JNICALL Java_com_example_emmc_NDKTest_emmc(JNIEnv *, jclass);

#ifdef __cplusplus
}


#endif
#endif

