/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
#include "../../../../../../../AndroidSdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_example_emmc_JniUtil */

#ifndef _Included_com_example_emmc_JniUtil
#define _Included_com_example_emmc_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_emmc_JniUtil
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
extern "C" JNIEXPORT jstring JNICALL Java_com_example_emmc_JniUtil_stringFromJNI
  (JNIEnv *env, jclass obj);

#ifdef __cplusplus
}
#endif
#endif
